pytest 8.3.4 has an empty newline after FAILURES

diff --git a/tests/test_run_examples.py b/tests/test_run_examples.py
index 33fc942..96d6793 100644
--- a/tests/test_run_examples.py
+++ b/tests/test_run_examples.py
@@ -163,7 +163,7 @@ def test_find_run_examples(example: CodeExample, eval_example: EvalExample):
 
     failures_start = next(index for index, line in enumerate(result.outlines) if 'FAILURES' in line)
     failures_end = next(index for index, line in enumerate(result.outlines) if 'short test summary' in line)
-    e_lines = [line.strip() for line in result.outlines[failures_start + 2 : failures_end]]
+    e_lines = [line.strip() for line in result.outlines[failures_start + 2 : failures_end] if line.strip()]
     assert e_lines == [
         'black failed:',
         '--- before',
@@ -197,7 +197,7 @@ def test_find_run_examples(example: CodeExample, eval_example: EvalExample):
 
     failures_start = next(index for index, line in enumerate(result.outlines) if 'FAILURES' in line)
     failures_end = next(index for index, line in enumerate(result.outlines) if 'short test summary' in line)
-    e_lines = [line.strip() for line in result.outlines[failures_start + 2 : failures_end]]
+    e_lines = [line.strip() for line in result.outlines[failures_start + 2 : failures_end] if line.strip()]
     assert e_lines == [
         'black failed:',
         '--- before',
@@ -239,7 +239,7 @@ def test_find_run_examples(example: CodeExample, eval_example: EvalExample):
 
     failures_start = next(index for index, line in enumerate(result.outlines) if 'FAILURES' in line)
     failures_end = next(index for index, line in enumerate(result.outlines) if 'short test summary' in line)
-    e_lines = [line.strip() for line in result.outlines[failures_start + 2 : failures_end]]
+    e_lines = [line.strip() for line in result.outlines[failures_start + 2 : failures_end] if line.strip()]
     assert e_lines == [
         'black failed:',
         '--- before',

